name: ponio-solver-doc

channels:
  - conda-forge

dependencies:
  - sympy
  - numpy
  - jinja2
  - matplotlib
  - cxx-compiler
  - cmake
  - ninja
  - pkg-config
  - eigen
  - cli11
  - pandoc
  - nbconvert
  - graphviz
  - doxygen
  - breathe
  - pydata-sphinx-theme
  - sphinxcontrib-bibtex
